-- MySQL Script generated by MySQL Workbench
-- Tue Apr 21 13:27:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RoomsDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RoomsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RoomsDB` DEFAULT CHARACTER SET utf8;
USE `RoomsDB`;

-- -----------------------------------------------------
-- Table `RoomsDB`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RoomsDB`.`rooms`
(
    `idRoom`      INT         NOT NULL,
    `roomName`    VARCHAR(45) NOT NULL,
    `counry`      VARCHAR(45) NOT NULL,
    `countryCode` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`idRoom`)
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
